name: Test

on:
  push:
    branches:
    - testing_ci
    
jobs:  
  build_container_job:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build container
      run: docker-compose build
    - name: run container and close it 
      run: |
      docker-compose up & 
      sleep 40 & 
      docker-compose down
    

  
  # vnc_connection_job:
  #   timeout-minutes: 5  
  #   needs: [build_container_job]
  #   runs-on: ubuntu-latest    
  #   steps:
  #   - name: connect the vnc viewer
  #     run: vncviewer 127.0.0.1:5900

  # close_docker_job:
  #   timeout-minutes: 5  
  #   needs: [vnc_connection_job]
  #   runs-on: ubuntu-latest    
  #   steps:
  #   - name: Close containers
  #     run: docker-compose down
