name: Test

on:
  push:
    branches:
    - testing_ci
    
jobs:  

  ubuntu_build_job:
    timeout-minutes: 35
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Start containers
      run: docker-compose up
  
  vnc_connection_job:
    - name: connect the vnc viewer
      run: vncviewer 127.0.0.1:5900

  close_docker_job:
    - name: Close containers
      run: docker-compose down
