name: Test

on:
  push:
    branches:
    - testing_ci
    
jobs:  

  ubuntu_build_job:
    timeout-minutes: 35
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Start containers
      run: make up
    - name: Stop containers
      run: make down 